name: UsersApp CI Pipeline

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches:
      - master

jobs:
  test_backend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11.6"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install users dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/users/requirements.txt

    - name: Run linters for users & common
      run: |
        flake8 backend/ 

    - name: Copy .env.example to backend/.env
      run: |
        cp .env.example backend/.env

    - name: Run tests for users
      run: |
        pytest users/
      working-directory: ./backend

  build_docker_compose:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker images
      run: |
        docker compose -f docker-compose.dev.yml build